### PR TITLE
random updates

### PR DESCRIPTION
**Pull request by mreiferson**
see commit message

### CODE REVIEW

**Comment by ploxiln** [comment]
it looks like, with this change, the coerce functions don't need to handle their own type anymore? e.g.

```go
func coerceDuration(v interface{}) (time.Duration, error) {
	...
	case time.Duration:
		return v.(time.Duration), nil
```

**Comment by ploxiln** [comment]
you could update to the go versions in the travis test matrix, probably fine to add to this branch

(and I wonder if you could/should manually back-date the go version in the go.mod file)

**Comment by ploxiln** [comment]
looks great to me

**Comment by mreiferson** [comment]
check that last commit @ploxiln, the `int*` cases need to still handle all varieties...

**Comment by ploxiln** [comment]
Yeah, removing self-support was a possible silly idea, sorry about that ... I see it's needed when you convert an int64 to a uint16 or by going through coerceInt64() first, or when you convert a float64 to a float32 by going through coerceFloat64() first.

Anyway, 👍

**Pull request merged**
